config/routes.rb
RorBlog::Application.routes.draw do

  get "password_resets/new"

  resources :sessions, only: :create
  resources :users
  resources :posts, except: :index
  resources :password_resets
  resources :comments, only: [:create, :destroy]
  resources :tags, only: :show

  match 'signup',   to: 'users#new'
  match 'activate/:id', to: 'users#activate', as: 'activate'
  match 'signin',   to: 'sessions#new'
  match 'signout',  to: 'sessions#destroy', via: :delete

  root :to => 'posts#index'

  match 'about' => "static_pages#about"

  mount Markitup::Rails::Engine, at: 'markitup', as: 'markitup'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_filter :expired_secret_token, only: [:edit, :update]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      flash[:info] = "Email sent with password reset instructions
                      to #{params[:email]}."
    else
      flash[:error] = "Not found user with email #{params[:email]}."
    end
    redirect_to root_path
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = 'Password has been updated.'
      redirect_to root_url
    else
      render :edit
    end
  end

  private

    def expired_secret_token
      @user = User.find_by_secret_token!(params[:id])
      if @user.secret_token_sent_at < 2.hours.ago
        flash[:error] = 'Password reset has expired.'
        redirect_to new_password_reset_url
      end
    end
end

app/views/password_resets/edit.html.slim
- provide :title, 'Update password'

.password_reset
  .row-fluid
    .span6.offset3
      h1 Update password

      = form_for @user, url: password_reset_path(params[:id]) do |f|

        == render 'shared/error_mesages', object: f.object

        = f.label :password
        = f.password_field :password

        = f.label :password_confirmation
        = f.password_field :password_confirmation

        = f.submit 'Update password', class: 'btn'

app/views/password_resets/new.html.slim
- provide :title, 'Reset password'

.password_reset
  .row-fluid
    .span6.offset3
      h1 Reset password

      = form_tag password_resets_path do

        = label_tag :email
        = text_field_tag :email

        = submit_tag 'Reset password', class: 'btn'