config/routes.rb
RorBlog::Application.routes.draw do

  get "password_resets/new"

  resources :sessions, only: :create
  resources :users
  resources :posts, except: :index
  resources :password_resets
  resources :comments, only: [:create, :destroy]
  resources :tags, only: :show

  match 'signup',   to: 'users#new'
  match 'activate/:id', to: 'users#activate', as: 'activate'
  match 'signin',   to: 'sessions#new'
  match 'signout',  to: 'sessions#destroy', via: :delete

  root :to => 'posts#index'

  match 'about' => "static_pages#about"

  mount Markitup::Rails::Engine, at: 'markitup', as: 'markitup'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_many :comments
  has_many :assignments
  has_many :roles, through: :assignments

  before_save { email.downcase! }
  before_create { generate_token :auth_token }

  validates :name, :email, :password_confirmation, presence: true
  validates :name, length: { minimum: 3, maximum: 50 },
    uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, presence: true, on: :update

  default_scope order: 'name'

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:secret_token)
    self.secret_token_sent_at = Time.zone.now
    save!(validate: false)
    UserMailer.password_reset(self).deliver
  end

  def send_activation_link
    generate_token(:secret_token)
    save!(validate: false)
    UserMailer.activate_account(self).deliver
  end

  def role?(symbol)
    role = Role.find_by_name(symbol.to_s)
    self.roles.include?(role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource except: :activate

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  end

  def new
  end

  def create
    if @user.save
      @user.send_activation_link
      flash[:success] = 'Activation link was sent to your email'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def activate
    user = User.find_by_secret_token!(params[:id])
    if user.update_attribute(:activated, true)
      flash[:success] = 'Your account was activated!'
    else
      flash[:error] = 'Activation failed'
    end
    redirect_to root_url
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = 'Profile was updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'Your account was deleted'
    redirect_to root_url
  end
end

app/views/users/_form_fields.html.slim
= render 'shared/error_mesages', object: f.object

= f.label :name
= f.text_field :name

= f.label :email
= f.text_field :email

= f.label :password
= f.password_field :password

= f.label :password_confirmation
= f.password_field :password_confirmation

app/views/users/_user.html.slim
tr
  td = link_to user.name, user
  td = user.email
  td
    =' link_to icon('file-alt'), user
    =' link_to icon('pencil'), edit_user_path(user)
    =' link_to icon('remove'), user, class: 'red', method: :delete,\
                                                   confirm: 'Are you sure?'

app/views/users/edit.html.slim
- provide(:title, 'Edit profile')

.row-fluid
  .span6.offset3
    h1 Edit profile
    = form_for(@user) do |f|
      = render 'form_fields', f: f
      = f.submit 'Save changes', class: "btn"

app/views/users/index.html.slim
- provide(:title, 'Users')

.users
  h1 Users

  table.table.table-hover.table-striped.table-condensed
    thead
      tr
        th Name
        th Email
        th
    tbody
      == render @users

  = will_paginate

app/views/users/new.html.slim
- provide(:title, 'Sign up')

.row-fluid
  .span6.offset3
    h1 Sign up
    = form_for(@user) do |f|
      = render 'form_fields', f: f
      = f.submit 'Sign up', class: "btn"

app/views/users/show.html.slim
- provide(:title, 'User profile')

.profile
  h1 User profile
  table
    tr
      td Name:
      td: b = @user.name
    tr
      td Email:
      td: b = @user.email
p
  =' link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-warning'
  = link_to 'Delete account', user_path(@user), class: 'btn btn-danger',
                                                method: :delete,
                                                confirm: 'Are you sure?'