config/routes.rb
RorBlog::Application.routes.draw do

  get "password_resets/new"

  resources :sessions, only: :create
  resources :users
  resources :posts, except: :index
  resources :password_resets
  resources :comments, only: [:create, :destroy]
  resources :tags, only: :show

  match 'signup',   to: 'users#new'
  match 'activate/:id', to: 'users#activate', as: 'activate'
  match 'signin',   to: 'sessions#new'
  match 'signout',  to: 'sessions#destroy', via: :delete

  root :to => 'posts#index'

  match 'about' => "static_pages#about"

  mount Markitup::Rails::Engine, at: 'markitup', as: 'markitup'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :content, :title, :tag_names

  has_many :comments, dependent: :destroy
  has_many :taggins, dependent: :destroy
  has_many :tags, through: :taggins

  attr_writer :tag_names

  default_scope order: 'created_at DESC'

  before_save :save_tag_names

  validates :title, :content, presence: true
  validates :title, length: { maximum: 100 }

  def tag_names
    @tag_names || tags.pluck(:name).join(', ')
  end

  def save_tag_names
    if @tag_names
      old_tags = self.tags.dup
      self.tags = @tag_names.split(', ').map do |name|
        tag = Tag.where(name: name).first_or_initialize
        tag.update_posts_count(1) unless old_tags.include? tag
        tag
      end
      old_tags.each do |old_tag|
        old_tag.update_posts_count(-1) unless self.tags.include? old_tag
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.includes(:tags).page(params[:page]).per_page(10)
  end

  def show
    @comment = @post.comments.build
    @comments = @post.comments.includes(:user)
  end

  def new
  end

  def create
    if @post.save
      flash[:success] = 'New post created!'
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:success] = 'Post updated!'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post was deleted!'
    redirect_to root_url
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
   tags.map { |tag| link_to tag.name, tag_path(tag) }
  end
end

app/views/posts/_post.html.slim
.post
  h1.title
    = link_to post.title, post
  .post-info
    = time_tag post.created_at
  .content
    == markdown(truncate(post.content, length: 1, separator: '<!--more-->'))

  .infopanel
    -if post.tags.any?
      .tags
        = icon('tag')
        == tag_links(post.tags).join(', ')

    .comments-count
      = icon('comments-alt')
      = link_to post.comments_count, "#{post_path(post)}/#comments"

    - if can? :update, post
      =' link_to icon('pencil'), edit_post_path(post)
    - if can? :destroy, post
      =' link_to icon('trash'), post_path(post),
                               class: 'red',
                               id: "delete_#{post.id}",
                               method: :delete,
                               confirm: 'Are you sure?'

    = link_to 'Read more →', post, class: 'btn btn-small pull-right'

app/views/posts/edit.html.slim
- provide(:title, 'Edit post')

.row-fluid
  .span10.offset1
    h1 Edit post
    = simple_form_for(@post) do |f|
      = f.input :title
      = f.input :content
      = f.input :tag_names
      = f.button :submit, 'Update post'

app/views/posts/index.html.slim
.posts
  - if @posts.any?
    == render @posts
    = will_paginate @posts

app/views/posts/new.html.slim
- provide(:title, 'New post creation')

.row-fluid
  .span10.offset1
    h1 Create new post
    = simple_form_for(@post) do |f|
      = f.input :title
      = f.input :content
      = f.input :tag_names
      = f.button :submit, 'Create post'

app/views/posts/show.html.slim
- provide(:title, @post.title)

article
  h1.title = @post.title
  = time_tag @post.created_at
  .content == markdown @post.content.gsub('<!--more-->', '')

  .infopanel
    -if @post.tags.any?
      .tags
        = icon('tag')
        == tag_links(@post.tags).join(', ')

hr
== render 'comments/form'
a name='comments'

- unless @comments.empty?
  hr
  .comments
    h4
      =' icon('comments-alt')
      | Comments(#{@post.comments_count})
    == render @comments