config/routes.rb
RorBlog::Application.routes.draw do

  get "password_resets/new"

  resources :sessions, only: :create
  resources :users
  resources :posts, except: :index
  resources :password_resets
  resources :comments, only: [:create, :destroy]
  resources :tags, only: :show

  match 'signup',   to: 'users#new'
  match 'activate/:id', to: 'users#activate', as: 'activate'
  match 'signin',   to: 'sessions#new'
  match 'signout',  to: 'sessions#destroy', via: :delete

  root :to => 'posts#index'

  match 'about' => "static_pages#about"

  mount Markitup::Rails::Engine, at: 'markitup', as: 'markitup'

end

app/views/layouts/_header.html.slim
header.navbar.navbar-static-top
  .navbar-inner
    .container
      = link_to "RoR Blog", root_path, id: "logo"
      nav
        ul.nav.pull-right
          li = link_to t('home'), root_path
          li = link_to t('about'), about_path
          - if signed_in?
            li = link_to icon('cogs'), current_user
            li = link_to icon('signout'), signout_path, method: :delete
          -else
            li = link_to icon('signin'), signin_path

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

app/views/layouts/_sidebar.html.slim
- if can? :create, Post
  = link_to 'Add post', new_post_path, class: 'btn btn-info'

ul.tags
  == render tags

app/views/layouts/application.html.slim
doctype 5
html
  head
    title = full_title(yield :title)
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    == render 'layouts/shim'
    script hljs.initHighlightingOnLoad();
  body
    == render 'layouts/header'
    .container-fluid
      .row-fluid
        .span9
          .main
            == render 'shared/flash', flash: flash
            = yield
        .span3.offset.9
          .sidebar
            == render 'layouts/sidebar'

app/views/layouts/markitup.html.slim
doctype 5
html
  head
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    == render 'layouts/shim'
    script hljs.initHighlightingOnLoad();
  body
    .container-fluid
      .row-fluid
        .span12
            article
              .content
                = yield